// Generated by gencpp from file chassis_drive/agvs_mode.msg
// DO NOT EDIT!


#ifndef CHASSIS_DRIVE_MESSAGE_AGVS_MODE_H
#define CHASSIS_DRIVE_MESSAGE_AGVS_MODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace chassis_drive
{
template <class ContainerAllocator>
struct agvs_mode_
{
  typedef agvs_mode_<ContainerAllocator> Type;

  agvs_mode_()
    : current_mode(0)  {
    }
  agvs_mode_(const ContainerAllocator& _alloc)
    : current_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _current_mode_type;
  _current_mode_type current_mode;



// reducing the odds to have name collisions with Windows.h 
#if defined(_WIN32) && defined(agvs_mode_manual)
  #undef agvs_mode_manual
#endif
#if defined(_WIN32) && defined(agvs_mode_auto_floor_1)
  #undef agvs_mode_auto_floor_1
#endif
#if defined(_WIN32) && defined(agvs_mode_auto_floor_2)
  #undef agvs_mode_auto_floor_2
#endif

  enum {
    agvs_mode_manual = 0u,
    agvs_mode_auto_floor_1 = 1u,
    agvs_mode_auto_floor_2 = 2u,
  };


  typedef boost::shared_ptr< ::chassis_drive::agvs_mode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::chassis_drive::agvs_mode_<ContainerAllocator> const> ConstPtr;

}; // struct agvs_mode_

typedef ::chassis_drive::agvs_mode_<std::allocator<void> > agvs_mode;

typedef boost::shared_ptr< ::chassis_drive::agvs_mode > agvs_modePtr;
typedef boost::shared_ptr< ::chassis_drive::agvs_mode const> agvs_modeConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::chassis_drive::agvs_mode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::chassis_drive::agvs_mode_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::chassis_drive::agvs_mode_<ContainerAllocator1> & lhs, const ::chassis_drive::agvs_mode_<ContainerAllocator2> & rhs)
{
  return lhs.current_mode == rhs.current_mode;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::chassis_drive::agvs_mode_<ContainerAllocator1> & lhs, const ::chassis_drive::agvs_mode_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace chassis_drive

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::chassis_drive::agvs_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::chassis_drive::agvs_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_drive::agvs_mode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::chassis_drive::agvs_mode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_drive::agvs_mode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::chassis_drive::agvs_mode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::chassis_drive::agvs_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "334b5039384f49ff4aa9ee0483feb402";
  }

  static const char* value(const ::chassis_drive::agvs_mode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x334b5039384f49ffULL;
  static const uint64_t static_value2 = 0x4aa9ee0483feb402ULL;
};

template<class ContainerAllocator>
struct DataType< ::chassis_drive::agvs_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "chassis_drive/agvs_mode";
  }

  static const char* value(const ::chassis_drive::agvs_mode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::chassis_drive::agvs_mode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 current_mode\n"
"\n"
"uint8 agvs_mode_manual =0\n"
"uint8 agvs_mode_auto_floor_1 = 1\n"
"uint8 agvs_mode_auto_floor_2 = 2\n"
;
  }

  static const char* value(const ::chassis_drive::agvs_mode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::chassis_drive::agvs_mode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct agvs_mode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::chassis_drive::agvs_mode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::chassis_drive::agvs_mode_<ContainerAllocator>& v)
  {
    s << indent << "current_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CHASSIS_DRIVE_MESSAGE_AGVS_MODE_H
