// Generated by gencpp from file agvs_control/slam_data.msg
// DO NOT EDIT!


#ifndef AGVS_CONTROL_MESSAGE_SLAM_DATA_H
#define AGVS_CONTROL_MESSAGE_SLAM_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace agvs_control
{
template <class ContainerAllocator>
struct slam_data_
{
  typedef slam_data_<ContainerAllocator> Type;

  slam_data_()
    : theta_x(0.0)
    , theta_y(0.0)
    , theta_angle(0.0)
    , speed_x(0.0)
    , speed_y(0.0)
    , speed_z(0.0)  {
    }
  slam_data_(const ContainerAllocator& _alloc)
    : theta_x(0.0)
    , theta_y(0.0)
    , theta_angle(0.0)
    , speed_x(0.0)
    , speed_y(0.0)
    , speed_z(0.0)  {
  (void)_alloc;
    }



   typedef float _theta_x_type;
  _theta_x_type theta_x;

   typedef float _theta_y_type;
  _theta_y_type theta_y;

   typedef float _theta_angle_type;
  _theta_angle_type theta_angle;

   typedef float _speed_x_type;
  _speed_x_type speed_x;

   typedef float _speed_y_type;
  _speed_y_type speed_y;

   typedef float _speed_z_type;
  _speed_z_type speed_z;





  typedef boost::shared_ptr< ::agvs_control::slam_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::agvs_control::slam_data_<ContainerAllocator> const> ConstPtr;

}; // struct slam_data_

typedef ::agvs_control::slam_data_<std::allocator<void> > slam_data;

typedef boost::shared_ptr< ::agvs_control::slam_data > slam_dataPtr;
typedef boost::shared_ptr< ::agvs_control::slam_data const> slam_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::agvs_control::slam_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::agvs_control::slam_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::agvs_control::slam_data_<ContainerAllocator1> & lhs, const ::agvs_control::slam_data_<ContainerAllocator2> & rhs)
{
  return lhs.theta_x == rhs.theta_x &&
    lhs.theta_y == rhs.theta_y &&
    lhs.theta_angle == rhs.theta_angle &&
    lhs.speed_x == rhs.speed_x &&
    lhs.speed_y == rhs.speed_y &&
    lhs.speed_z == rhs.speed_z;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::agvs_control::slam_data_<ContainerAllocator1> & lhs, const ::agvs_control::slam_data_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace agvs_control

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::agvs_control::slam_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::agvs_control::slam_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvs_control::slam_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::agvs_control::slam_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvs_control::slam_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::agvs_control::slam_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::agvs_control::slam_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "91db6ffd3f1cb419025d2f1a637f02e6";
  }

  static const char* value(const ::agvs_control::slam_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x91db6ffd3f1cb419ULL;
  static const uint64_t static_value2 = 0x025d2f1a637f02e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::agvs_control::slam_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "agvs_control/slam_data";
  }

  static const char* value(const ::agvs_control::slam_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::agvs_control::slam_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 theta_x\n"
"float32 theta_y\n"
"float32 theta_angle\n"
"float32 speed_x\n"
"float32 speed_y\n"
"float32 speed_z\n"
;
  }

  static const char* value(const ::agvs_control::slam_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::agvs_control::slam_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.theta_x);
      stream.next(m.theta_y);
      stream.next(m.theta_angle);
      stream.next(m.speed_x);
      stream.next(m.speed_y);
      stream.next(m.speed_z);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct slam_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::agvs_control::slam_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::agvs_control::slam_data_<ContainerAllocator>& v)
  {
    s << indent << "theta_x: ";
    Printer<float>::stream(s, indent + "  ", v.theta_x);
    s << indent << "theta_y: ";
    Printer<float>::stream(s, indent + "  ", v.theta_y);
    s << indent << "theta_angle: ";
    Printer<float>::stream(s, indent + "  ", v.theta_angle);
    s << indent << "speed_x: ";
    Printer<float>::stream(s, indent + "  ", v.speed_x);
    s << indent << "speed_y: ";
    Printer<float>::stream(s, indent + "  ", v.speed_y);
    s << indent << "speed_z: ";
    Printer<float>::stream(s, indent + "  ", v.speed_z);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AGVS_CONTROL_MESSAGE_SLAM_DATA_H
